create table personal (empid integer, name varchar(20), bloodgroup varchar(20),emergencynbr integer);
insert into personal values(100,'ram','O+ve',04692602206);
insert into personal values(101,'samue;','AB+ve',9946673789);
insert into personal values(102,'ram','B-ve',7034788724);
commit;
create table offical1(empid integer,department varchar(20), salary integer);
insert into offical1 values(100,'cus&mark',90000);
insert into offical1 values(101,'coredev',50000);
insert into offical1 values(102,'stat&ana',70000);
commit;
select * from offical1;
select p.name ,p.bloodgroup,o.department,o.salary from personal p, offical1 o;
select p.name ,p.bloodgroup,o.department,o.salary from personal p, offical1 o where p.empid = o.empid;

select s.name from sailor s where s.sid IN ( select  r.sid from reserv r where bid='b004');
select s.name from sailor s , reserv r where s.sid =r.sid and bid='b004';
select s.name from sailor s where exists (select * from reserv r where r.bid='b004' and r.sid=s.sid);
create table product(pid integer primary key, pname varchar(20));
insert into product values(1,'curry powder');
insert into product values(2,'toys');
commit;
drop table product;
alter table dept add constraint pk  primary key(deptno );
create table customer1 (cid integer primary key, cname varchar(20));
insert into customer1 values(100,'vatsala');
 CREATE TABLE author (authorid int primary key, authorname varchar(20));
 create table books (bookid int primary key, authorid int ,bookname varchar(20));
 alter table books add constraint fk foreign key(authorid) references author(authorid) ;
 alter table bonus add constraint ck check( sal in(50000,150000));
 commit;
create table emp1(empid integer primary key,empname varchar(20),mngrid varchar(20)); 
drop table emp1;
create table emp1(empid integer primary key,empname varchar(20),mngrid integer); 
insert into emp1 values(1,'ram',2);
insert into emp1 values(2,'stephen',3);
insert into emp1 values(3,'kannan',0);
insert into emp1 values(4,'sruthi',2);
insert into emp1 values(5,'radhika',2);
 select e.empname,m.empname from emp1 e, emp1 m where e.mngrid= m.empid;
 commit;